pipeline {

  agent any
  
  triggers {
    pollSCM '* * * * *'
  }
  environment {
    CI = 'true'
    HOME = '.'
    npm_config_cache = 'npm-cache'
  }
  
  post {
    failure {
      updateGitlabCommitStatus name: 'build', state: 'failed'
    }
    success {
      updateGitlabCommitStatus name: 'build', state: 'success'
    }
  }
  
  options {
    gitLabConnection('GitLab Connection')
  }
  
  stages {
    stage('Install Packages') {
      steps {
        sh 'npm install'
      }
    }
	stage('Run Tests') {
        steps {
			sh 'npm run test'
        }
    }
    stage('Build Artifacts') {
        steps {
          sh 'npm run build'
        }
    }  
    stage('AWS: Deployment') {
          when {
            branch 'master'
          }
          steps {
            withAWS(region:'ap-south-1',credentials:'c9fb9e69-d6e9-4279-8be8-0a39978d84e4') {
              s3Delete(bucket: 'travelappweb', path:'')
              s3Upload(bucket: 'travelappweb', workingDir:'dist/TravelAppUI', includePathPattern:'**/*');
            }
            //mail(subject: 'Production Build', body: 'New Deployment to Production', to: 'jenkins-mailing-list@mail.com')
          }
    }
  }
}